#!/usr/bin/env bash

set -eu

script_dir=$(cd $(dirname $0); pwd)

cd ~/edk2
set +u
. edksetup.sh
set -u
build
~/osbook/devenv/run_qemu.sh ~/edk2/Build/MikanLoaderX64/DEBUG_CLANG38/X64/Loader.efi ~/workspace/mikanos/kernel/kernel.elf
